name       : systemd-bootchart
version    : 233
release    : 2
source     :
    - https://github.com/systemd/systemd-bootchart/releases/download/v233/systemd-bootchart-233.tar.xz : f4cb17b21928e36ec27de5c5294dea6ec1de4acd7ee6c56d6ecc75319cbcaefa
license    :
    - GPL-2.0-only
    - LGPL-2.1-only
component  : system.boot
summary    : Boot performance graphing tool
description: |
    Boot performance graphing tool
builddeps  :
    - pkgconfig(libsystemd)
    - docbook-xml
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
